### ISSUE TITLE
sfdiagram not functioning

### ISSUE THREAD

**Issue by tfsmag** [rflechner/LinqToSalesforce#29]
### Description

sfdiagram file has been created, and the required values have been filled in. After clicking authenticate nothing happens. This is in visual studio profressional 2017

### Expected behavior

After clicking authentication it should allow you to select entities according to documentation.

### Actual behavior

Nothing happens after clicking the authenticate button.

**Comment by rflechner** [comment]
Hi, could you try with this version?
 
https://www.myget.org/feed/romcyber/package/vsix/LinqToSalesforce.VsPlugin.d8cf1da6-2ca2-4879-ba36-133827f9c342

**Comment by paraplexed** [comment]
I'm seeing the same issue when hitting `Authenticate` on VS community 2017. 

I tried using the updated plugin you linked @rflechner but it seems to have the same issue of nothing ever happening.

Is there a some logs or something I can pull to give you more debug information? If there is, let me know where those logs would be stored.

**Comment by HaAzzoug** [comment]
Hi,
It's work fine with the new version v0.2.9.3
https://github.com/rflechner/LinqToSalesforce/releases/tag/0.2.9.3

**Comment by rflechner** [comment]
Hi,

I found solution in PR #32.

Could you use version 0.2.9.3 ?

https://github.com/rflechner/LinqToSalesforce/releases/tag/0.2.9.3

Regards.
